MUSIC_CATALOG = [
    # Energetic
    {"id": "1", "title": "Blinding Lights", "artist": "The Weeknd", "genre": "synth-pop", "mood": "energetic", "duration_sec": 200},
    {"id": "2", "title": "Uptown Funk", "artist": "Bruno Mars", "genre": "pop", "mood": "energetic", "duration_sec": 270},
    {"id": "3", "title": "Can't Stop the Feeling", "artist": "Justin Timberlake", "genre": "pop", "mood": "energetic", "duration_sec": 236},
    {"id": "4", "title": "Don't Stop Me Now", "artist": "Queen", "genre": "rock", "mood": "energetic", "duration_sec": 209},
    {"id": "5", "title": "Titanium", "artist": "David Guetta ft. Sia", "genre": "electronic", "mood": "energetic", "duration_sec": 245},
    {"id": "6", "title": "Levels", "artist": "Avicii", "genre": "electronic", "mood": "energetic", "duration_sec": 180},
    {"id": "7", "title": "Thunder", "artist": "Imagine Dragons", "genre": "rock", "mood": "energetic", "duration_sec": 187},
    {"id": "8", "title": "Stronger", "artist": "Kanye West", "genre": "hip-hop", "mood": "energetic", "duration_sec": 312},
    {"id": "9", "title": "Scary Monsters", "artist": "Skrillex", "genre": "electronic", "mood": "energetic", "duration_sec": 274},
    {"id": "10", "title": "Run the World", "artist": "Beyoncé", "genre": "pop", "mood": "energetic", "duration_sec": 236},
    # Calm
    {"id": "11", "title": "Weightless", "artist": "Marconi Union", "genre": "ambient", "mood": "calm", "duration_sec": 480},
    {"id": "12", "title": "Clair de Lune", "artist": "Debussy", "genre": "classical", "mood": "calm", "duration_sec": 348},
    {"id": "13", "title": "Breathe", "artist": "Télépopmusik", "genre": "electronic", "mood": "calm", "duration_sec": 265},
    {"id": "14", "title": "Gymnopédie No. 1", "artist": "Erik Satie", "genre": "classical", "mood": "calm", "duration_sec": 210},
    {"id": "15", "title": "Holocene", "artist": "Bon Iver", "genre": "indie", "mood": "calm", "duration_sec": 337},
    {"id": "16", "title": "The Night We Met", "artist": "Lord Huron", "genre": "indie", "mood": "calm", "duration_sec": 207},
    {"id": "17", "title": "River Flows in You", "artist": "Yiruma", "genre": "classical", "mood": "calm", "duration_sec": 186},
    {"id": "18", "title": "Skinny Love", "artist": "Bon Iver", "genre": "indie", "mood": "calm", "duration_sec": 232},
    {"id": "19", "title": "Saturn", "artist": "Sleeping at Last", "genre": "indie", "mood": "calm", "duration_sec": 270},
    {"id": "20", "title": "Bloom", "artist": "The Paper Kites", "genre": "indie", "mood": "calm", "duration_sec": 234},
    # Happy
    {"id": "21", "title": "Happy", "artist": "Pharrell Williams", "genre": "pop", "mood": "happy", "duration_sec": 233},
    {"id": "22", "title": "Here Comes the Sun", "artist": "The Beatles", "genre": "rock", "mood": "happy", "duration_sec": 185},
    {"id": "23", "title": "Walking on Sunshine", "artist": "Katrina and the Waves", "genre": "pop", "mood": "happy", "duration_sec": 239},
    {"id": "24", "title": "Good Vibrations", "artist": "The Beach Boys", "genre": "rock", "mood": "happy", "duration_sec": 219},
    {"id": "25", "title": "Three Little Birds", "artist": "Bob Marley", "genre": "reggae", "mood": "happy", "duration_sec": 180},
    {"id": "26", "title": "I Gotta Feeling", "artist": "Black Eyed Peas", "genre": "pop", "mood": "happy", "duration_sec": 289},
    {"id": "27", "title": "Best Day of My Life", "artist": "American Authors", "genre": "rock", "mood": "happy", "duration_sec": 194},
    {"id": "28", "title": "Lovely Day", "artist": "Bill Withers", "genre": "soul", "mood": "happy", "duration_sec": 254},
    {"id": "29", "title": "Mr. Blue Sky", "artist": "Electric Light Orchestra", "genre": "rock", "mood": "happy", "duration_sec": 305},
    {"id": "30", "title": "Dancing Queen", "artist": "ABBA", "genre": "pop", "mood": "happy", "duration_sec": 232},
    # Motivational
    {"id": "31", "title": "Lose Yourself", "artist": "Eminem", "genre": "hip-hop", "mood": "motivational", "duration_sec": 326},
    {"id": "32", "title": "Eye of the Tiger", "artist": "Survivor", "genre": "rock", "mood": "motivational", "duration_sec": 245},
    {"id": "33", "title": "Stronger", "artist": "Kelly Clarkson", "genre": "pop", "mood": "motivational", "duration_sec": 222},
    {"id": "34", "title": "Fight Song", "artist": "Rachel Platten", "genre": "pop", "mood": "motivational", "duration_sec": 204},
    {"id": "35", "title": "Hall of Fame", "artist": "The Script", "genre": "pop", "mood": "motivational", "duration_sec": 202},
    {"id": "36", "title": "Remember the Name", "artist": "Fort Minor", "genre": "hip-hop", "mood": "motivational", "duration_sec": 229},
    {"id": "37", "title": "Believer", "artist": "Imagine Dragons", "genre": "rock", "mood": "motivational", "duration_sec": 204},
    {"id": "38", "title": "Till I Collapse", "artist": "Eminem", "genre": "hip-hop", "mood": "motivational", "duration_sec": 297},
    {"id": "39", "title": "We Will Rock You", "artist": "Queen", "genre": "rock", "mood": "motivational", "duration_sec": 122},
    {"id": "40", "title": "Born This Way", "artist": "Lady Gaga", "genre": "pop", "mood": "motivational", "duration_sec": 260},
    # Melancholy
    {"id": "41", "title": "Someone Like You", "artist": "Adele", "genre": "pop", "mood": "melancholy", "duration_sec": 285},
    {"id": "42", "title": "Mad World", "artist": "Gary Jules", "genre": "indie", "mood": "melancholy", "duration_sec": 193},
    {"id": "43", "title": "Hurt", "artist": "Johnny Cash", "genre": "country", "mood": "melancholy", "duration_sec": 217},
    {"id": "44", "title": "Everybody Hurts", "artist": "R.E.M.", "genre": "rock", "mood": "melancholy", "duration_sec": 312},
    {"id": "45", "title": "Fix You", "artist": "Coldplay", "genre": "rock", "mood": "melancholy", "duration_sec": 295},
    {"id": "46", "title": "Nothing Compares 2 U", "artist": "Sinéad O'Connor", "genre": "pop", "mood": "melancholy", "duration_sec": 310},
    {"id": "47", "title": "Tears in Heaven", "artist": "Eric Clapton", "genre": "rock", "mood": "melancholy", "duration_sec": 274},
    {"id": "48", "title": "The Sound of Silence", "artist": "Simon & Garfunkel", "genre": "folk", "mood": "melancholy", "duration_sec": 187},
    {"id": "49", "title": "Creep", "artist": "Radiohead", "genre": "rock", "mood": "melancholy", "duration_sec": 238},
    {"id": "50", "title": "Black", "artist": "Pearl Jam", "genre": "rock", "mood": "melancholy", "duration_sec": 342},
]
